name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run BE and FE in background
        run: |
          npm run start-be &
          npm run start-fe &
          sleep 10  # Wait for 10 seconds to allow servers to start
      - name: Run Integration Tests
        run: npx playwright test tests/ui.test.js

  deploy_to_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: integration_tests
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4

      - name: Deploy Web Service to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.MY_RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "${{ secrets.MY_RENDER_WEB_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.MY_RENDER_WEB_SERVICE_ID }}/deploys

      - name: Deploy Static Site to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.MY_RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "${{ secrets.MY_RENDER_STATIC_SITE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.MY_RENDER_STATIC_SITE_ID }}/deploys
