name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   ui_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run BE  in backgroud
        run: npm run start-be &
      - name: Run FE in backgroud    
        run: npm run start-fe &
      - name: Run UI Tests
        run: npx playwright test tests/ui.test.js

   deploy_to_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: ui_tests
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4

      # Deploy the web service
      - name: Deploy Web Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_WEB_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      
      # Deploy the static site
      - name: Deploy Static Site to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_STATIC_SITE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
